# English translations for vigilo-connector-nagios.
# Copyright (C) 2010 ORGANIZATION
# This file is distributed under the same license as the
# vigilo-connector-nagios
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: vigilo-connector-nagios 2.0.0\n"
"Report-Msgid-Bugs-To: contact@projet-vigilo.org\n"
"POT-Creation-Date: 2010-04-23 15:21+0200\n"
"PO-Revision-Date: 2010-04-23 15:23+0200\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: en <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/connector_nagios/main.py:68
#: src/vigilo/connector_nagios/main.py:80
#, python-format
msgid "Directory not found: '%(dir)s'"
msgstr "Directory not found: '%(dir)s'"

#: src/vigilo/connector_nagios/main.py:73
#: src/vigilo/connector_nagios/main.py:85
#, python-format
msgid "Wrong permissions on directory: '%(dir)s'"
msgstr "Wrong permissions on directory: '%(dir)s'"

#: src/vigilo/connector_nagios/main.py:92
#, python-format
msgid "Can't write to the Nagios command pipe: '%s'"
msgstr "Can't write to the Nagios command pipe: '%s'"

#: src/vigilo/connector_nagios/main.py:96
#, python-format
msgid "Can't traverse directory: '%(dir)s'"
msgstr "Can't traverse directory: '%(dir)s'"

#: src/vigilo/connector_nagios/xmpptopipefw.py:43
msgid "Connection initialized"
msgstr "Connection initialized"

#: src/vigilo/connector_nagios/xmpptopipefw.py:110
msgid ""
"The configured nagios command pipe is not a FIFO. Storing message for "
"later."
msgstr ""
"The configured nagios command pipe is not a FIFO. Storing message for "
"later."

#: src/vigilo/connector_nagios/xmpptopipefw.py:123
#, python-format
msgid "Writing to %s: %s"
msgstr "Writing to %s: %s"

#: src/vigilo/connector_nagios/xmpptopipefw.py:132
#, python-format
msgid ""
"Unable to forward message %(error_message)s, this message is stored for "
"later reemission."
msgstr ""
"Unable to forward message %(error_message)s, this message is stored for "
"later reemission."

#: src/vigilo/connector_nagios/xmpptopipefw.py:161
#, python-format
msgid "Unrecognized message type: '%s'"
msgstr "Unrecognized message type: '%s'"

#: src/vigilo/connector_nagios/xmpptopipefw.py:169
#, python-format
msgid ""
"Command '%(received)s' disallowed by policy, accepted commands: "
"%(accepted)r"
msgstr ""
"Command '%(received)s' disallowed by policy, accepted commands: "
"%(accepted)r"

#: src/vigilo/connector_nagios/xmpptopipefw.py:176
#, python-format
msgid "Command message to forward: ts=%s name=%s val=%s"
msgstr "Command message to forward: ts=%s name=%s val=%s"

